# apiVersion: backstage.io/v1alpha1
# kind: API
# metadata:
#   namespace: default
#   name: pp-login-api
# relations:
#   - type: ownedBy
#     targetRef: group:default/guests
#     target:
#       kind: group
#       namespace: default
#       name: guests
#   - type: partOf
#     targetRef: system:default/examples
#     target:
#       kind: system
#       namespace: default
#       name: examples
# spec:
#   type: grpc
#   lifecycle: experimental
#   owner: guests
#   system: examples
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pp-backend-apis
  description: PP Login API
spec:
  type: openapi
  lifecycle: experimental
  owner: Adas
  system: publisher-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: PP API
      license:
        name: Coda
    servers:
      - url: http://pp-be.com/v1
             http://staging.pp-be.com/v1
    paths:
      /login:
        get:
          summary: Validate login credentials of users
      /settlement:
        get:
          summary: Fetches settlement based permissions
      /profile:
        get:
          summary: Retrieves user's profile data
      /dashboard:
        get:
          summary: Last 7 days Transaction's summary data 
