apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: default
  name: pp-login-api
relations:
  - type: ownedBy
    targetRef: group:default/guests
    target:
      kind: group
      namespace: default
      name: guests
  - type: partOf
    targetRef: system:default/examples
    target:
      kind: system
      namespace: default
      name: examples
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
